### ISSUE TITLE
[Lua datamodel] Wrong behaviour if function assigned to <data> element

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#116]
Hello, after assigning function to \<data\> element its content is evaluating. I think that this is wrong behaviour

```
<scxml datamodel="lua" initial="StateShape1" name="ScxmlShape1" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<datamodel>
		<data expr="0" id="Var1"/>
		<data id="ChangeVar1">function ()
    print(&quot;We must not see it!&quot;)
    Var1 = 555
end
		</data>
	</datamodel>
	<state id="StateShape1">
		<transition cond="Var1==0" target="Pass"/>
		<transition cond="Var1==555" target="Fail"/>
	</state>
	<final id="Pass"/>
	<final id="Fail"/>
</scxml>
```

**Comment by sradomski** [comment]
I guess the issue is `evalAsData` vs `getAsData`. I will have to check at various places for consistent usage.

**Comment by sradomski** [comment]
The problem is in `getLuaAsData` from the [LuaDataModel:83](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/plugins/datamodel/lua/LuaDataModel.cpp#L83). In order to assign a `Data` object to the location, I evaluate the function. The data object cannot hold a function as a _first class citizen_ because there is no way to do that in a datamodel agnostic way. You are, however, perfectly free to use a script element to assign whatever you like to wherever you like it.
