### ISSUE TITLE
uscxml issue when same scxml is invoked more than once

### ISSUE THREAD

**Issue by parora1701** [tklab-tud/uscxml#121]
Expected behaviour: when a scxml is invoked twice, variables declared in "invoked" scxml should contain values independent to other invokes.

Currently, value from the second invoke overwrites the value set by first invoke.

Attached two scxml to reproduce issue. 

[parent.scxml.txt](https://github.com/tklab-tud/uscxml/files/975931/parent.scxml.txt)
[child.scxml.txt](https://github.com/tklab-tud/uscxml/files/975932/child.scxml.txt)

**Comment by alexzhornyak** [comment]
This is because your scxml code is badly designed!
Compare, how it could be
![2017-05-04 15 29 25](https://cloud.githubusercontent.com/assets/18611095/25703589/ddf596c0-30de-11e7-965b-a87e39e5ea52.png)
![2017-05-04 15 29 29](https://cloud.githubusercontent.com/assets/18611095/25703597/e7b66504-30de-11e7-9487-6febd7d6c14f.png)
![2017-05-04 15 31 32](https://cloud.githubusercontent.com/assets/18611095/25703604/ecd09b18-30de-11e7-8906-ccc3f6a8e05f.png)
[parent.scxml](https://github.com/tklab-tud/uscxml/files/976108/parent.scxml.txt)
[child.scxml](https://github.com/tklab-tud/uscxml/files/976109/child.scxml.txt)

**Comment by parora1701** [comment]
Can you please explain why my scxml was badly design? As I ran scxml provided by you and getting same error. 
![parent_output](https://cloud.githubusercontent.com/assets/5223842/25704533/1cca638a-30da-11e7-8081-be98acd51232.PNG)

**Comment by alexzhornyak** [comment]
About bad design: I didn't like that scxml doesn't have final state and hungs. I agree that this is not the reason of issue.

The reason is promela datamodel, because, for example, with lua datamodel your code works as you planned.
![2017-05-04 16 48 15](https://cloud.githubusercontent.com/assets/18611095/25706603/935dc7bc-30e9-11e7-8665-3f9ba0763328.png)

**Comment by parora1701** [comment]
I was designing dining philosopher problem which is not supposed to have final state(well, at least theoretically). Thank you for confirming though that the issue is with promela datamodel.

**Comment by sradomski** [comment]
I cannot look into this until the upcoming weekend, but thank you for reporting it!

**Comment by sradomski** [comment]
I just had a look at it .. what am I supposed to see? I do get a `var1` reported in `s01` of the parent as `1` and another one as `2`. Is that not correct? You do pass `p_id` as `1` and `2` respectively and just return them, do you not?

**Comment by parora1701** [comment]
Hi, did you check with PROMELA datamodel as @alexzhornyak also stated it is working as expected with LUA datamodel.
I tried again and still `var1` value in `s01` of _parent.scxml_ is 2 for both invokes. 
![log](https://cloud.githubusercontent.com/assets/5223842/25889784/58a93d28-356b-11e7-9748-a01ee9ac934c.JPG)
Maybe I can try fetching the latest if its a recent fix.

**Comment by sradomski** [comment]
Can you please confirm that this is still an issue with the latest submit?

**Comment by parora1701** [comment]
Yes of'course, I will confirm by this evening, I just don't have my laptop with me at the moment.

**Comment by parora1701** [comment]
Hello, I have confirmed this is no longer an issue and `var1` is indeed showing value `1` and `2` respectively when ran with the latest build. Thank you.
