### ISSUE TITLE
How to read the "content" string serialized in the invoke structure

### ISSUE THREAD

**Issue by xmarduel** [tklab-tud/uscxml#136]
Hello,
from the uscxml-transform I obtain the following c file with

static const uscxml_elem_invoke _uscxml_6132F30D__elem_invokes[1] = {
    { 
        /* machine     */ NULL, 
        /* type        */ "ads2", 
        /* typeexpr    */ NULL, 
        /* src         */ NULL, 
        /* srcexpr     */ NULL, 
        /* id          */ NULL, 
        /* idlocation  */ NULL, 
        /* sourcename  */ "world", 
        /* namelist    */ NULL, 
        /* autoforward */ 0, 
        /* params      */ NULL, 
        /* finalize    */ _uscxml_6132F30D__world_invoke0_finalize0, 
        /* content      */ "0x1a5c9800x1a5ca200x1a5cd300x1a5cdd00x1a5d090", 
        /* contentexpr  */ NULL, 
    }
};

This is from
<invoke type="ads2">
        <content>
                <set name="var3" value="1" />
                <set name="var3" value="11" />
        </content>
        <finalize>
               <assign expr="_event.data" location="var3"/>
        </finalize>
</invoke>

the "content" is a stringstream (see ChartToC.cpp) from 

std::stringstream ss;
DOMNodeList* cChilds = contents.front()->getChildNodes();
for (size_t j = 0; j < cChilds->getLength(); j++) {
	ss << cChilds->item(j);
}
stream << "        /* content      */ ";
stream << (ss.str().size() > 0 ? "\"" + escape(ss.str()) + "\", " : "NULL, ") << std::endl;

In my own "invoke" handler, I get back the content as "0x1a5c9800x1a5ca200x1a5cd300x1a5cdd00x1a5d090", but do I read this (i.e. get a DOMNodeList * or the "real" content from this) ?

Thank you for your help and tips.
Sincerely

XM

**Comment by sradomski** [comment]
Haha, there is a dereference missing, you get the `operator<<` of the pointer, not the actual object. I will fix it in a bit.

**Comment by sradomski** [comment]
I did fix and will push in a second. Please, if you report bugs, do provide a small SCXML file for me to check. It's most appreciated if you can have it end in `<final id="pass">` or `<final id="fail">` depending on whether the issue is solved or not. That way, I can easily add it as a regression test to make sure it will not pop up again in the future. See the [issue tests here](https://github.com/tklab-tud/uscxml/tree/master/test/issues).

Reopen if I messed up - I have not tested it.
