### ISSUE TITLE
Use Case Examples

### ISSUE THREAD

**Issue by inertCoder** [tklab-tud/uscxml#154]
I've been going over uscxml and I really like it. I'm currently trying to use it embedded in a C# application. I setup a little console app, got the interpreter working, and all looks good. My issue is I'm trying to figure out how to catch events or variables from the scxml in the C# code. 

[Here](https://github.com/tklab-tud/uscxml/files/1120170/test.txt) I have a little test scxml file, I'm trying to figure out multiple things:
1) How to catch the changed event
2) How to get the current value of the Var1 variable

Do I need to use a send event to get the Var1 variable data? If so how would I do that?

I brought up the issue because I think it would be extremely helpful if there were some examples provided on how to use uscxml, other than how to get the interpreter running. If there are some and I missed them could you please point me into the right direction?

Thank you very much, any help is appreciated!

**Comment by sradomski** [comment]
You extend and register [InterpreterMonitors](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/interpreter/InterpreterMonitor.h). I am about to change this specific system into lambdas, but they would not translate into the bindings. However, I am thinking about allowing lambdas via a small wrapper in the target languages as well. For now try with InterpreterMonitors, I'll push something for lambdas within the week.

**Comment by inertCoder** [comment]
Thank you very much and for the quick response! I was able to setup my own custom class and catch an event no problem. So, if I want to get and edit the datamodel and all the data inside from the scxml and in the C# code, would I have to extend the DataModel or DataModelImpl class?

**Comment by sradomski** [comment]
I have to admit that the C# bindings did not yet see the same attention as, e.g., the Java Bindings, but should work exactly the same. For the Java bindings, there is a complete example with JEXL as a custom datamodel [here](https://github.com/tklab-tud/uscxml/tree/master/contrib/java/common/org/uscxml/dm/jexl).

It passes all the W3C tests as you can confirm by running:

    ctest -L "w3c/binding/java/jexl"

The tests are defined [here](https://github.com/tklab-tud/uscxml/blob/master/test/CMakeLists.txt#L420) and are executed via the wrapper [here](https://github.com/tklab-tud/uscxml/blob/master/test/ctest/scripts/test_generated_java.cmake).

The DataModel class is a PIMPL facade for any given DataModelImpl instantiated by the Factory depending on the `datamodel` attribute of the SCXML document. In order to register target language classes as extensions and provide a API more suited for target language types, the C++ `DataModel` class is [renamed](https://github.com/tklab-tud/uscxml/blob/master/src/bindings/swig/uscxml_beautify.i#L3) to `DataModelNative` and the `WrappedDataModel` https://github.com/tklab-tud/uscxml/blob/master/src/bindings/swig/wrapped/WrappedDataModel.h is moved in its place. This is the class that you need to extend / implement (we cannot easily create interface with SWIG) and register instances at an Interpreter's ActionLanguage as is done in the example [here](https://github.com/tklab-tud/uscxml/blob/master/contrib/java/bindings/org/uscxml/tests/JexlDataModelTest.java#L49).

The `DataModelExtension` class is a relict to bind values from the target language into the datamodel and vice verse. We did suspend its support as it violated the `events are the source of all state changes` axiom, but I could be tempted to rethink that.

If there is a C# pendant to JEXL, I may have a student of ours implement a respective datamodel in C#, very much like the JEXL datamodel in Java.

**Comment by sradomski** [comment]
Oh, and if you want to query one of the existing DataModels in the target languages, you can retrieve the interpreter's instance via the `getActionLanguage` and the DataModel instance inside. Then you can get values via `evalAsData()`. Be careful though that you can change the state of the DataModel and may introduce state changes not caused by events. This may lead to surprising behavior at times.

At least that's how it is working in C++ and I sincerely hope that SWIG managed to refelct this functionality in all target langauges as well. If not, feel free to reopen issue.
