### ISSUE TITLE
Value Returned in Event.data is Wrapped in Quotes

### ISSUE THREAD

**Issue by skalemkiewicz** [tklab-tud/uscxml#159]
I'm not sure if this is expected behavior or not.

I have a C# class overriding `InterpreterMonitor.beforeProcessingEvent(Interpreter interpreter, Event arg1)`. When I "send" an event containing data using the `<content/>` tag, a call to `arg1.data.ToString()` returns the `<content/>` tag and its children. However, the string itself starts and ends with a double quote.

If I have the following in SCXML:
```xml
<send event="my-event">
    <content>
        <mydatatag/>
    </content>
</send>
```

I get the following string back:
```xml
"\r\n<content xmlns=\"http://www.w3.org/2005/07/scxml\">\n<mydatatag/>\n</content>"
```

I would expect to get back (note no enclosing quotes):
```xml
\r\n<content xmlns=\"http://www.w3.org/2005/07/scxml\">\n<mydatatag/>\n</content>
```

It may even be preferable to not have to call `System.Text.RegularExpressions.Regex.Unescape()` to convert the escaped line endings.

**Comment by sradomski** [comment]
Please be aware that the signature of all callbacks in the monitors was changed: the first formal parameter is no longer the interpreter instance but its sessionId due to performance reasons. If you need the interpreter, you have to get it via Interpreter::fromSessionId.

With regard to your actual question, `ToString()` [triggers](https://github.com/tklab-tud/uscxml/blob/master/src/bindings/swig/csharp/uscxml.i#L158) the `operator<<` in C++ as specified [here](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/messages/Data.cpp#L207). That operator serializes the complete structure into a JSON object, thus the quotes. If you were to send structured data, it would be received as a proper JSON structure.
